### ISSUE TITLE
Settings page hints/steps

### ISSUE THREAD

**Issue by caiokf** [caiokf/what-language#21]
some info to the user to make clear what steps he should take

**Comment by samjam48** [comment]
Languages options should appear when landing on the page so that when user gets the map it is actually a map for them.

Should be obvious how to remove a language.

**Comment by caiokf** [comment]
> when user gets the map it is actually a map for them.

what is "them"?. not sure i understood this sentence overall

**Comment by samjam48** [comment]
Basically, the map they user first sees should be a map of the languages that they speak. Thus it is "a map for them".

Or perhaps blank but I don't think having a bunch of default languages in there when they starti s good.

**Comment by caiokf** [comment]
ahh yes, i agree. i plan to persist the redux state to localstorage and then start empty or with english only for new users, but for now that was the easiest for me to test
