### ISSUE TITLE
Fluent Second Language

### ISSUE THREAD

**Issue by caiokf** [caiokf/what-language#6]
- [ ] Create data for second language where country is usually fluent
- [ ] Allow options to be toggled for second language or just official language

**Comment by samjam48** [comment]
are you going to hard code this with the info you just know about places? or access an api?

**Comment by caiokf** [comment]
idea was to start with the places i know. if anybody actually uses this, i could open for user feedback. but i was working with the assumption that would be hard to find an api that does that.

**Comment by samjam48** [comment]
Good plan. Just an option to send info of a place. or allow people to actually add info directly in the app?

**Comment by caiokf** [comment]
well. it qouod need to be reviewed first, but yes they would send info throigh the app somehow
